MorningBriefing/urls.py
from django.conf.urls import url
from MorningBriefing import views
app_name = 'MorningBriefing'
urlpatterns = [
	url(r'^$',views.index, name = 'home'),
	url(r'^발전사동향/',views.a, name='발전사동향'),
	url(r'^파워인사이트/',views.Powerinsight, name='파워인사이트'),
	url(r'^전력산업/시장/',views.b, name='전력산업/시장'),
	url(r'^신재생에너지/기술/',views.c, name='신재생에너지/기술'),
	url(r'^경제/에너지/',views.d ,name='경제/에너지'),
	url(r'^(?P<pk>\d+)/add_comment_to_post/$',views.add_comment_to_post, name='add_comment_to_post'),
	url(r'^(?P<pk>\d+)/delete/$',views.delete,name='delete_news'),
	url(r'^(?P<pk>\d+)/delete/$',views.delete_news,name='delete'),
	url(r'^보고서/',views.report ,name='보고서'),
	url(r'^보고서초기화/',views.reportinitialize ,name='보고서초기화'),
	url(r'^(?P<pk>\d+)/modify_title/$',views.modify_title, name='modify_title'),
	
]

WEB/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('MorningBriefing.urls')),
]

MorningBriefing/models.py
from django.db import models
import datetime
from django.utils import timezone
class News(models.Model):
    Title = models.CharField(max_length=200) #<title>{% News.title%}</title>
    Link = models.CharField(max_length=2000, unique=True) #a href = {% News.link[]%}
    Comment = models.TextField(
        
        blank = True, 

        default = None)
    Published_date = models.DateField(default =timezone.now)

    Select = (
        ('A', '발전사 동향'), # 한전 #남동발전 #한국전력 #동서발전 #..... -- > 
        ('B', '전력산업/시장'), #전력 #이병준 #주병권
        ('C', '신재생에너지/기술'),
        ('D', '경제/에너지'),
    )
    
    Data_field = models.CharField(
        max_length = 1,
        choices = Select,
        blank = True,
        default = 'm',
    )
    class Meta:
        ordering = ['Data_field', 'Published_date' ]

class Report(models.Model):
	idx = models.AutoField(primary_key=True)
	site = models.CharField(max_length=50)
	title = models.TextField(default = None)
	link = models.TextField(default = None)
	published_date = models.DateField(default = None)

MorningBriefing/forms.py
from django import forms
from .models import News
from .models import Report
class CommentForm(forms.ModelForm): #forms의 ModelForm 클래스를 상속 받는다.

    class Meta:
        model = News
        fields = ('Comment', )
class NewTitleForm(forms.ModelForm): #forms의 ModelForm 클래스를 상속 받는다.

    class Meta:
        model = News
        fields = ('Title',)

MorningBriefing/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import News, Report
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse
from .forms import CommentForm, NewTitleForm
from django.views.decorators.csrf import csrf_exempt
import json
from django.template import loader
from datetime import timedelta
import datetime
from django.db.models import Q


def index(request):
	news = News.objects.all()
	context = {'news' :news}
	return render(request, 'MorningBriefing/index.html',context)


def Powerinsight(request):
	report = Report.objects.all()
	context = {'report' :report}
	return render(request, 'MorningBriefing/Powerinsight.html',context)


@csrf_exempt
def a(request):
	today=datetime.date.today()
	one_day_ago = today-datetime.timedelta(days=1)
	try:
		start_date=request.POST["start_date"]
	except:
		start_date="2019-01-01"
	try:
		end_date=request.POST["end_date"]
	except:
		end_date=today
	try:
		search=request.POST["search"]
	except:
		search=""
	start_date=start_date if start_date else one_day_ago
	end_date=end_date if end_date else today
	news = News.objects.filter(Q(Published_date__gte=start_date, Published_date__lte=end_date)&Q(Title__contains=search))
	context = {'news':news,}
	return render(request, 'MorningBriefing/a.html',context)

def b(request):
	today=datetime.date.today()
	one_day_ago = today-datetime.timedelta(days=1)
	try:
		start_date=request.POST["start_date"]
	except:
		start_date="2019-01-01"
	try:
		end_date=request.POST["end_date"]
	except:
		end_date=today
	try:
		search=request.POST["search"]
	except:
		search=""
	start_date=start_date if start_date else one_day_ago
	end_date=end_date if end_date else today
	news = News.objects.filter(Q(Published_date__gte=start_date, Published_date__lte=end_date)&Q(Title__contains=search))
	context = {'news':news,}
	return render(request, 'MorningBriefing/b.html',context)

def c(request):
	today=datetime.date.today()
	one_day_ago = today-datetime.timedelta(days=1)
	try:
		start_date=request.POST["start_date"]
	except:
		start_date="2019-01-01"
	try:
		end_date=request.POST["end_date"]
	except:
		end_date=today
	try:
		search=request.POST["search"]
	except:
		search=""
	start_date=start_date if start_date else one_day_ago
	end_date=end_date if end_date else today
	news = News.objects.filter(Q(Published_date__gte=start_date, Published_date__lte=end_date)&Q(Title__contains=search))
	context = {'news':news,}
	return render(request, 'MorningBriefing/c.html',context)

def d(request):
	today=datetime.date.today()
	one_day_ago = today-datetime.timedelta(days=1)
	try:
		start_date=request.POST["start_date"]
	except:
		start_date="2019-01-01"
	try:
		end_date=request.POST["end_date"]
	except:
		end_date=today
	try:
		search=request.POST["search"]
	except:
		search=""
	start_date=start_date if start_date else one_day_ago
	end_date=end_date if end_date else today
	news = News.objects.filter(Q(Published_date__gte=start_date, Published_date__lte=end_date)&Q(Title__contains=search))
	context = {'news':news,}
	return render(request, 'MorningBriefing/d.html',context)

def report(request):
	news = News.objects.all()
	context = {'news':news,}
	return render(request, 'MorningBriefing/report.html',context)

def reportinitialize(request):
	news = News.objects.filter(Comment__isnull=False)
	for news in news:
		news.Comment=''
		news.save()
	return HttpResponseRedirect("/")
	

def comment_detail(request,pk):
	news = get_object_or_404(News,pk=pk)
	return render(request, 'MorningBriefing/comment_detail.html',{'news':news})


def add_comment_to_post(request,pk):
	news = get_object_or_404(News,pk=pk)

	if request.method == "POST":
		comment_form = CommentForm(request.POST)

		if CommentForm(request.POST).is_valid():
			news = News.objects.get(pk=pk)
			comment_form = CommentForm(request.POST, instance = news)
			comment_form.save()

			if news.Data_field == 'A':
				return HttpResponseRedirect("/발전사동향")
			if news.Data_field == 'B':
				return HttpResponseRedirect("/전력산업/시장")
			if news.Data_field == 'C':
				return HttpResponseRedirect("/신재생에너지/기술")
			if news.Data_field == 'D':
				return HttpResponseRedirect("/경제/에너지")
	else:
		form = CommentForm()
	return render(request, 'MorningBriefing/add_comment_to_post.html',{'news':news, 'form':form})


def delete(request,pk):
	news = get_object_or_404(News,pk=pk)
	news.Comment = ''
	news.save()
	if news.Data_field == 'A':		
		return redirect("/발전사동향")
	if news.Data_field == 'B':
		return redirect("/전력산업/시장")
	if news.Data_field == 'C':
		return redirect("/신재생에너지/기술")
	if news.Data_field == 'D':
		return redirect("/경제/에너지")

def delete_news(request,pk):
	news = get_object_or_404(News,pk=pk)
	news.delete()
	if news.Data_field == 'A':		
		return redirect("/발전사동향")
	if news.Data_field == 'B':
		return redirect("/전력산업/시장")
	if news.Data_field == 'C':
		return redirect("/신재생에너지/기술")
	if news.Data_field == 'D':
		return redirect("/경제/에너지")

def modify_title(request,pk):
	news = get_object_or_404(News,pk=pk)

	if request.method == "POST":
		new_title = NewTitleForm(request.POST)

		if NewTitleForm(request.POST).is_valid():
			news = News.objects.get(pk=pk)
			new_title = NewTitleForm(request.POST, instance = news)
			new_title.save()

			if news.Data_field == 'A':
				return HttpResponseRedirect("/발전사동향")
			if news.Data_field == 'B':
				return HttpResponseRedirect("/전력산업/시장")
			if news.Data_field == 'C':
				return HttpResponseRedirect("/신재생에너지/기술")
			if news.Data_field == 'D':
				return HttpResponseRedirect("/경제/에너지")
	else:
		form = NewTitleForm()
	return render(request, 'MorningBriefing/modify_title.html',{'news':news, 'form':form})

MorningBriefing/templates/MorningBriefing/a.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Morning Briefing</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'MorningBriefing:home' %}">Home</a>
      </div>
      <ul class="nav navbar-nav">
        <li>
        </li>
        <li><a href = "{% url 'MorningBriefing:발전사동향' %}">발전사동향</a></li>
        <li><a href = "{% url 'MorningBriefing:전력산업/시장'%}">전력산업/시장</a></li>
        <li><a href = "{% url 'MorningBriefing:신재생에너지/기술'%}">신재생에너지/기술</a></li>
        <li><a href = "{% url 'MorningBriefing:경제/에너지'%}">경제/에너지</a></li>
        <li><a href = "{% url 'MorningBriefing:파워인사이트'%}">파워인사이트</a></li>
        <li><a href = "{% url 'MorningBriefing:보고서'%}">보고서</a></li>

      </ul>
    </div>
  </nav>

<div class="container">
    <table class="table table-striped">
        <thead> 
        <tr>
            <td><B><font size=10>발전사동향</font></B></td> 
            <td style= "width:50px">
              <form method="post">
                {% csrf_token %}
                
                <div style="text-align: left"><font size = 3><B>start date<input type="date" style = "text-align: right;border: 0px; font-size: 3" name="start_date" value="{{start_date}}"></B></font>
                <div style="text-align: left"><font size = 3><B>end  date<input type="date" style = "text-align: right;border: 0px; font-size: 3" name="end_date" value="{{end_date}}"></B></font>
                <input name="search" value="{{search}}">
                <input type="submit" class="btn btn-success" value="검색">
              
              </form>
            </td>
           
        </tr>
        </thead>        

        <tbody> 


            {% for news in news %}

            {% if news.Data_field == 'A' %}
        <tr>

            <td>


                <div>
                    <p><font size=3>{{news.Title}}({{news.Published_date}})</font></p>
                    <p>{{news.Comment}}</p>

                </div>
              </span>
              <div align="right">
                <div class="btn-group">
                  <button type="submit" class="btn btn-success"  style="text-align:right;" onclick="window.open('{{news.Link}}')">Go</button>
                  <a class="btn btn-light" href="{%url 'MorningBriefing:modify_title' pk=news.pk %}">Modify_title</a>
                  <a class="btn btn-primary" href="{%url 'MorningBriefing:add_comment_to_post' pk=news.pk %}">Add comment</a>
                <a href="{% url 'MorningBriefing:delete_news' pk=news.pk %}" class="btn btn-warning del" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">Delete comment</a>
              <a href="{% url 'MorningBriefing:delete' pk=news.pk %}" class="btn btn-danger del" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">Delete News</a>
              </div>
              </div>
 
            {% endif %}
          </td>
        </tr>
        {% endfor %}
    </script>
          

        </tbody>
    </table>
</body>

MorningBriefing/templates/MorningBriefing/add_comment_to_post.html
<h1>New comment</h1>
<form method="POST" class="post-form" ;width=device-width>
  {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Send</button>
</form>

MorningBriefing/templates/MorningBriefing/b.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Morning Briefing</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'MorningBriefing:home' %}">Home</a>
      </div>
      <ul class="nav navbar-nav">
        <li>
        </li>
        <li><a href = "{% url 'MorningBriefing:발전사동향' %}">발전사동향</a></li>
        <li><a href = "{% url 'MorningBriefing:전력산업/시장'%}">전력산업/시장</a></li>
        <li><a href = "{% url 'MorningBriefing:신재생에너지/기술'%}">신재생에너지/기술</a></li>
        <li><a href = "{% url 'MorningBriefing:경제/에너지'%}">경제/에너지</a></li>
        <li><a href = "{% url 'MorningBriefing:파워인사이트'%}">파워인사이트</a></li>
        <li><a href = "{% url 'MorningBriefing:보고서'%}">보고서</a></li>

      </ul>
    </div>
  </nav>

<div class="container">
    <table class="table table-striped">
        <thead> 
        <tr>
            <td><B><font size=10>전력산업/시장</font></B></td>   
            <td style= "width:50px">
              <form method="post">
                {% csrf_token %}
                
                <div style="text-align: left"><font size = 3><B>start date<input type="date" style = "text-align: right;border: 0px; font-size: 3" name="start_date" value="{{start_date}}"></B></font>
                <div style="text-align: left"><font size = 3><B>end  date<input type="date" style = "text-align: right;border: 0px; font-size: 3" name="end_date" value="{{end_date}}"></B></font>
                <input name="search" value="{{search}}">
                <input type="submit" class="btn btn-success" value="검색">
              
              </form>
            </td>
        </tr>
        </thead>

        <tbody>       

            {% for news in news %}

            {% if news.Data_field == 'B' %}
        <tr>

            <td>


                <div>
                    <p><font size=3>{{news.Title}}({{news.Published_date}})</font></p>
                    <p>{{news.Comment}}</p>

                </div>
              </span>
              <div align="right">
                <div class="btn-group">
                  <button type="submit" class="btn btn-success"  style="text-align:right;" onclick="window.open('{{news.Link}}')">Go</button>
                  <a class="btn btn-light" href="{%url 'MorningBriefing:modify_title' pk=news.pk %}">Modify_title</a>
                  <a class="btn btn-primary" href="{%url 'MorningBriefing:add_comment_to_post' pk=news.pk %}">Add comment</a>
                <a href="{% url 'MorningBriefing:delete_news' pk=news.pk %}" class="btn btn-warning del" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">Delete comment</a>
              <a href="{% url 'MorningBriefing:delete' pk=news.pk %}" class="btn btn-danger del" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">Delete News</a>
              </div>
              </div>
 
            {% endif %}
          </td>
        </tr>
        {% endfor %}
    </script>
          

        </tbody>
    </table>
</body>

MorningBriefing/templates/MorningBriefing/c.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Morning Briefing</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'MorningBriefing:home' %}">Home</a>
          </div>
          <ul class="nav navbar-nav">
            <li>
            </li>
            <li><a href = "{% url 'MorningBriefing:발전사동향' %}">발전사동향</a></li>
            <li><a href = "{% url 'MorningBriefing:전력산업/시장'%}">전력산업/시장</a></li>
            <li><a href = "{% url 'MorningBriefing:신재생에너지/기술'%}">신재생에너지/기술</a></li>
            <li><a href = "{% url 'MorningBriefing:경제/에너지'%}">경제/에너지</a></li>
            <li><a href = "{% url 'MorningBriefing:파워인사이트'%}">파워인사이트</a></li>
            <li><a href = "{% url 'MorningBriefing:보고서'%}">보고서</a></li>

          </ul>
        </div>
      </nav>

<div class="container">
    <table class="table table-striped">
        <thead> 
        <tr>
            <td><B><font size=10>신재생에너지/기술</font></B></td>   
            <td style= "width:50px">
              <form method="post">
                {% csrf_token %}
                
                <div style="text-align: left"><font size = 3><B>start date<input type="date" style = "text-align: right;border: 0px; font-size: 3" name="start_date" value="{{start_date}}"></B></font>
                <div style="text-align: left"><font size = 3><B>end  date<input type="date" style = "text-align: right;border: 0px; font-size: 3" name="end_date" value="{{end_date}}"></B></font>
                <input name="search" value="{{search}}">
                <input type="submit" class="btn btn-success" value="검색">
              
              </form>
            </td>
        </tr>
        </thead>

        <tbody>       

            {% for news in news %}

            {% if news.Data_field == 'C' %}
        <tr>

            <td>


                <div>
                   <p><font size=3>{{news.Title}}({{news.Published_date}})</font></p>
                  <p>{{news.Comment}}</p>

                </div>
              </span>
              <div align="right">
                <div class="btn-group">
                  <button type="submit" class="btn btn-success"  style="text-align:right;" onclick="window.open('{{news.Link}}')">Go</button>
                  <a class="btn btn-light" href="{%url 'MorningBriefing:modify_title' pk=news.pk %}">Modify_title</a>
                  <a class="btn btn-primary" href="{%url 'MorningBriefing:add_comment_to_post' pk=news.pk %}">Add comment</a>
                <a href="{% url 'MorningBriefing:delete_news' pk=news.pk %}" class="btn btn-warning del" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">Delete comment</a>
              <a href="{% url 'MorningBriefing:delete' pk=news.pk %}" class="btn btn-danger del" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">Delete News</a>
              </div>
              </div>
 
            {% endif %}
          </td>
        </tr>
        {% endfor %}
    </script>
          

        </tbody>
    </table>
</body>

MorningBriefing/templates/MorningBriefing/d.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Morning Briefing</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'MorningBriefing:home' %}">Home</a>
      </div>
      <ul class="nav navbar-nav">
        <li>
        </li>
        <li><a href = "{% url 'MorningBriefing:발전사동향' %}">발전사동향</a></li>
        <li><a href = "{% url 'MorningBriefing:전력산업/시장'%}">전력산업/시장</a></li>
        <li><a href = "{% url 'MorningBriefing:신재생에너지/기술'%}">신재생에너지/기술</a></li>
        <li><a href = "{% url 'MorningBriefing:경제/에너지'%}">경제/에너지</a></li>
        <li><a href = "{% url 'MorningBriefing:파워인사이트'%}">파워인사이트</a></li>
        <li><a href = "{% url 'MorningBriefing:보고서'%}">보고서</a></li>

      </ul>
    </div>
  </nav>

<div class="container">
    <table class="table table-striped">
        <thead> 
        <tr>
            <td><B><font size=10>경제/에너지</font></B></td>  
            <td style= "width:50px">
              <form method="post">
                {% csrf_token %}
                
                <div style="text-align: left"><font size = 3><B>start date<input type="date" style = "text-align: right;border: 0px; font-size: 3" name="start_date" value="{{start_date}}"></B></font>
                <div style="text-align: left"><font size = 3><B>end  date<input type="date" style = "text-align: right;border: 0px; font-size: 3" name="end_date" value="{{end_date}}"></B></font>
                <input name="search" value="{{search}}">
                <input type="submit" class="btn btn-success" value="검색">
              
              </form>
            </td> 
        </tr>
        </thead>
        <tbody>       

            {% for news in news %}

            {% if news.Data_field == 'D' %}
        <tr>

            <td>


                <div>
                    <p><font size=3>{{news.Title}}({{news.Published_date}})</font></p>
                    <p>{{news.Comment}}</p>

                </div>
              </span>
              <div align="right">
                <div class="btn-group">
                  <button type="submit" class="btn btn-success"  style="text-align:right;" onclick="window.open('{{news.Link}}')">Go</button>
                  <a class="btn btn-light" href="{%url 'MorningBriefing:modify_title' pk=news.pk %}">Modify_title</a>
                  <a class="btn btn-primary" href="{%url 'MorningBriefing:add_comment_to_post' pk=news.pk %}">Add comment</a>
                <a href="{% url 'MorningBriefing:delete_news' pk=news.pk %}" class="btn btn-warning del" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">Delete comment</a>
              <a href="{% url 'MorningBriefing:delete' pk=news.pk %}" class="btn btn-danger del" role="button" onclick="return confirm('정말 삭제하시겠습니까?')">Delete News</a>
              </div>
              </div>
 
            {% endif %}
          </td>
        </tr>
        {% endfor %}
    </script>
          

        </tbody>
    </table>
</body>

MorningBriefing/templates/MorningBriefing/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Morning Briefing</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
   
<div class="container">
    <table class="table table-striped">
        <thead> 
        <tr>
            <td><B><font size=10>
                TREND

            </font></B></td>   
        </tr>
        </thead>
<tbody>


    <tr>
        <td>
                <div class="btn-group btn-group-justified" style = "text-align: center">
                        <button type= "button"  onclick="location.href='발전사동향' ">발전사동향</button>
                        <button type= "button"  onclick="location.href='전력산업/시장' ">전력산업/시장</button>
                        <button type= "button"  onclick="location.href='신재생에너지/기술' ">신재생에너지/기술</button>
                        <button type= "button"  onclick="location.href='경제/에너지' ">경제/에너지</button>
                        <button type= "button"  onclick="location.href='보고서' ">보고서</button>
                        <button type= "button"  onclick="location.href='파워인사이트' ">파워인사이트</button>
                        <button type= "button" href="{% url 'MorningBriefing:보고서초기화' %}"onclick="return confirm('정말 삭제하시겠습니까?')">보고서초기화</button>
                    </div>     
        </td>
       
      
       </div>
     </tr>
          
          
          
      
        <tbody>
    </table>
</body>

MorningBriefing/templates/MorningBriefing/modify_title.html
<h1>New comment</h1>
<form method="POST" class="post-form">
  {% csrf_token %}
    {{ form.as_p }}
    <p><font size=3  onclick="window.open('{{news.Link}}')" >기존 제목 : {{news.Title}}</font></p>
    <button type="submit" class="save btn btn-default" >Send</button>
</form>